// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/cel_validation.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderType represents different order types
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_STANDARD    OrderType = 1
	OrderType_ORDER_TYPE_EXPRESS     OrderType = 2
	OrderType_ORDER_TYPE_PRIORITY    OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_STANDARD",
		2: "ORDER_TYPE_EXPRESS",
		3: "ORDER_TYPE_PRIORITY",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_STANDARD":    1,
		"ORDER_TYPE_EXPRESS":     2,
		"ORDER_TYPE_PRIORITY":    3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cel_validation_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_cel_validation_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{0}
}

// PaymentMethod represents different payment methods
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD   PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD    PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_PAYPAL        PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_PAYPAL",
		4: "PAYMENT_METHOD_BANK_TRANSFER",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_CREDIT_CARD":   1,
		"PAYMENT_METHOD_DEBIT_CARD":    2,
		"PAYMENT_METHOD_PAYPAL":        3,
		"PAYMENT_METHOD_BANK_TRANSFER": 4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cel_validation_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_cel_validation_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{1}
}

// ConditionalOrder demonstrates conditional required fields using CEL
type ConditionalOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// orderType determines if expressFee is required
	OrderType OrderType `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3,enum=proto.OrderType" json:"order_type,omitempty"`
	// expressFee is required when orderType is EXPRESS
	ExpressFee    *float64 `protobuf:"fixed64,2,opt,name=express_fee,json=expressFee,proto3,oneof" json:"express_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionalOrder) Reset() {
	*x = ConditionalOrder{}
	mi := &file_proto_cel_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalOrder) ProtoMessage() {}

func (x *ConditionalOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cel_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalOrder.ProtoReflect.Descriptor instead.
func (*ConditionalOrder) Descriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ConditionalOrder) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *ConditionalOrder) GetExpressFee() float64 {
	if x != nil && x.ExpressFee != nil {
		return *x.ExpressFee
	}
	return 0
}

// AgeRestrictedProduct demonstrates cross-field validation using CEL
type AgeRestrictedProduct struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// productName is required
	ProductName string `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// minAge is the minimum age required to purchase
	MinAge int32 `protobuf:"varint,2,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	// userAge is the age of the user attempting to purchase
	UserAge       int32 `protobuf:"varint,3,opt,name=user_age,json=userAge,proto3" json:"user_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgeRestrictedProduct) Reset() {
	*x = AgeRestrictedProduct{}
	mi := &file_proto_cel_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgeRestrictedProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeRestrictedProduct) ProtoMessage() {}

func (x *AgeRestrictedProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cel_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeRestrictedProduct.ProtoReflect.Descriptor instead.
func (*AgeRestrictedProduct) Descriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{1}
}

func (x *AgeRestrictedProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *AgeRestrictedProduct) GetMinAge() int32 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *AgeRestrictedProduct) GetUserAge() int32 {
	if x != nil {
		return x.UserAge
	}
	return 0
}

// DiscountCoupon demonstrates conditional validation based on numeric comparison
type DiscountCoupon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// couponCode is required
	CouponCode string `protobuf:"bytes,1,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	// discountPercent must be between 0 and 100
	DiscountPercent *float64 `protobuf:"fixed64,2,opt,name=discount_percent,json=discountPercent,proto3,oneof" json:"discount_percent,omitempty"`
	// minPurchase is the minimum purchase amount required
	MinPurchase   float64 `protobuf:"fixed64,3,opt,name=min_purchase,json=minPurchase,proto3" json:"min_purchase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscountCoupon) Reset() {
	*x = DiscountCoupon{}
	mi := &file_proto_cel_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountCoupon) ProtoMessage() {}

func (x *DiscountCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cel_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountCoupon.ProtoReflect.Descriptor instead.
func (*DiscountCoupon) Descriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{2}
}

func (x *DiscountCoupon) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *DiscountCoupon) GetDiscountPercent() float64 {
	if x != nil && x.DiscountPercent != nil {
		return *x.DiscountPercent
	}
	return 0
}

func (x *DiscountCoupon) GetMinPurchase() float64 {
	if x != nil {
		return x.MinPurchase
	}
	return 0
}

// PaymentInfo demonstrates enum-based conditional validation
type PaymentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// paymentMethod determines which additional fields are required
	PaymentMethod PaymentMethod `protobuf:"varint,1,opt,name=payment_method,json=paymentMethod,proto3,enum=proto.PaymentMethod" json:"payment_method,omitempty"`
	// cardNumber is required for CREDIT_CARD and DEBIT_CARD
	CardNumber *string `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3,oneof" json:"card_number,omitempty"`
	// paypalEmail is required for PAYPAL
	PaypalEmail *string `protobuf:"bytes,3,opt,name=paypal_email,json=paypalEmail,proto3,oneof" json:"paypal_email,omitempty"`
	// bankAccount is required for BANK_TRANSFER
	BankAccount   *string `protobuf:"bytes,4,opt,name=bank_account,json=bankAccount,proto3,oneof" json:"bank_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_proto_cel_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cel_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentInfo) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentInfo) GetCardNumber() string {
	if x != nil && x.CardNumber != nil {
		return *x.CardNumber
	}
	return ""
}

func (x *PaymentInfo) GetPaypalEmail() string {
	if x != nil && x.PaypalEmail != nil {
		return *x.PaypalEmail
	}
	return ""
}

func (x *PaymentInfo) GetBankAccount() string {
	if x != nil && x.BankAccount != nil {
		return *x.BankAccount
	}
	return ""
}

// DateRange demonstrates date comparison validation
type DateRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// startDate must be before endDate
	StartDate int64 `protobuf:"varint,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// endDate must be after startDate
	EndDate       int64 `protobuf:"varint,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_proto_cel_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cel_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_proto_cel_validation_proto_rawDescGZIP(), []int{4}
}

func (x *DateRange) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *DateRange) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

var File_proto_cel_validation_proto protoreflect.FileDescriptor

const file_proto_cel_validation_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/cel_validation.proto\x12\x05proto\x1a\x1bbuf/validate/validate.proto\"\xc3\x02\n" +
	"\x10ConditionalOrder\x12<\n" +
	"\n" +
	"order_type\x18\x01 \x01(\x0e2\x10.proto.OrderTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\torderType\x124\n" +
	"\vexpress_fee\x18\x02 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00H\x00R\n" +
	"expressFee\x88\x01\x01:\xaa\x01\xbaH\xa6\x01\x1a\xa3\x01\n" +
	"\x14express_fee_required\x12;expressFee is required when orderType is ORDER_TYPE_EXPRESS\x1aNthis.order_type != proto.OrderType.ORDER_TYPE_EXPRESS || has(this.express_fee)B\x0e\n" +
	"\f_express_fee\"\x80\x02\n" +
	"\x14AgeRestrictedProduct\x12/\n" +
	"\fproduct_name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\vproductName\x12%\n" +
	"\amin_age\x18\x02 \x01(\x05B\f\xbaH\t\xc8\x01\x01\x1a\x04\x18d(\x12R\x06minAge\x12(\n" +
	"\buser_age\x18\x03 \x01(\x05B\r\xbaH\n" +
	"\xc8\x01\x01\x1a\x05\x18\x96\x01(\x00R\auserAge:f\xbaHc\x1aa\n" +
	"\x0fage_requirement\x12/userAge must be greater than or equal to minAge\x1a\x1dthis.user_age >= this.min_age\"\x8b\x03\n" +
	"\x0eDiscountCoupon\x12:\n" +
	"\vcoupon_code\x18\x01 \x01(\tB\x19\xbaH\x16\xc8\x01\x01r\x11\x10\x03\x18\x142\v^[A-Z0-9]+$R\n" +
	"couponCode\x12G\n" +
	"\x10discount_percent\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00H\x00R\x0fdiscountPercent\x88\x01\x01\x124\n" +
	"\fmin_purchase\x18\x03 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\vminPurchase:\xa8\x01\xbaH\xa4\x01\x1a\xa1\x01\n" +
	"#discount_required_for_high_purchase\x12@discountPercent is required when minPurchase is greater than 100\x1a8this.min_purchase <= 100.0 || has(this.discount_percent)B\x13\n" +
	"\x11_discount_percent\"\x98\a\n" +
	"\vPaymentInfo\x12H\n" +
	"\x0epayment_method\x18\x01 \x01(\x0e2\x14.proto.PaymentMethodB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\rpaymentMethod\x128\n" +
	"\vcard_number\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\v^\\d{13,19}$H\x00R\n" +
	"cardNumber\x88\x01\x01\x12/\n" +
	"\fpaypal_email\x18\x03 \x01(\tB\a\xbaH\x04r\x02`\x01H\x01R\vpaypalEmail\x88\x01\x01\x121\n" +
	"\fbank_account\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\n" +
	"\x18\"H\x02R\vbankAccount\x88\x01\x01:\xee\x04\xbaH\xea\x04\x1a\x87\x02\n" +
	"\x14card_number_required\x12DcardNumber is required for CREDIT_CARD or DEBIT_CARD payment methods\x1a\xa8\x01(this.payment_method != proto.PaymentMethod.PAYMENT_METHOD_CREDIT_CARD && this.payment_method != proto.PaymentMethod.PAYMENT_METHOD_DEBIT_CARD) || has(this.card_number)\x1a\xa6\x01\n" +
	"\x15paypal_email_required\x121paypalEmail is required for PAYPAL payment method\x1aZthis.payment_method != proto.PaymentMethod.PAYMENT_METHOD_PAYPAL || has(this.paypal_email)\x1a\xb4\x01\n" +
	"\x15bank_account_required\x128bankAccount is required for BANK_TRANSFER payment method\x1aathis.payment_method != proto.PaymentMethod.PAYMENT_METHOD_BANK_TRANSFER || has(this.bank_account)B\x0e\n" +
	"\f_card_numberB\x0f\n" +
	"\r_paypal_emailB\x0f\n" +
	"\r_bank_account\"\xbe\x01\n" +
	"\tDateRange\x12)\n" +
	"\n" +
	"start_date\x18\x01 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02 \x00R\tstartDate\x12%\n" +
	"\bend_date\x18\x02 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02 \x00R\aendDate:_\xbaH\\\x1aZ\n" +
	"\x0fend_after_start\x12&endDate must be greater than startDate\x1a\x1fthis.end_date > this.start_date*q\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ORDER_TYPE_STANDARD\x10\x01\x12\x16\n" +
	"\x12ORDER_TYPE_EXPRESS\x10\x02\x12\x17\n" +
	"\x13ORDER_TYPE_PRIORITY\x10\x03*\xab\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\x03\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x04B\"Z validation-service/backend/protob\x06proto3"

var (
	file_proto_cel_validation_proto_rawDescOnce sync.Once
	file_proto_cel_validation_proto_rawDescData []byte
)

func file_proto_cel_validation_proto_rawDescGZIP() []byte {
	file_proto_cel_validation_proto_rawDescOnce.Do(func() {
		file_proto_cel_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cel_validation_proto_rawDesc), len(file_proto_cel_validation_proto_rawDesc)))
	})
	return file_proto_cel_validation_proto_rawDescData
}

var file_proto_cel_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_cel_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cel_validation_proto_goTypes = []any{
	(OrderType)(0),               // 0: proto.OrderType
	(PaymentMethod)(0),           // 1: proto.PaymentMethod
	(*ConditionalOrder)(nil),     // 2: proto.ConditionalOrder
	(*AgeRestrictedProduct)(nil), // 3: proto.AgeRestrictedProduct
	(*DiscountCoupon)(nil),       // 4: proto.DiscountCoupon
	(*PaymentInfo)(nil),          // 5: proto.PaymentInfo
	(*DateRange)(nil),            // 6: proto.DateRange
}
var file_proto_cel_validation_proto_depIdxs = []int32{
	0, // 0: proto.ConditionalOrder.order_type:type_name -> proto.OrderType
	1, // 1: proto.PaymentInfo.payment_method:type_name -> proto.PaymentMethod
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cel_validation_proto_init() }
func file_proto_cel_validation_proto_init() {
	if File_proto_cel_validation_proto != nil {
		return
	}
	file_proto_cel_validation_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_cel_validation_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_cel_validation_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cel_validation_proto_rawDesc), len(file_proto_cel_validation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cel_validation_proto_goTypes,
		DependencyIndexes: file_proto_cel_validation_proto_depIdxs,
		EnumInfos:         file_proto_cel_validation_proto_enumTypes,
		MessageInfos:      file_proto_cel_validation_proto_msgTypes,
	}.Build()
	File_proto_cel_validation_proto = out.File
	file_proto_cel_validation_proto_goTypes = nil
	file_proto_cel_validation_proto_depIdxs = nil
}
