// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/complex_validation.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShippingType represents different shipping methods
type ShippingType int32

const (
	ShippingType_SHIPPING_TYPE_UNSPECIFIED ShippingType = 0
	ShippingType_SHIPPING_TYPE_DIGITAL     ShippingType = 1
	ShippingType_SHIPPING_TYPE_PHYSICAL    ShippingType = 2
	ShippingType_SHIPPING_TYPE_EXPRESS     ShippingType = 3
)

// Enum value maps for ShippingType.
var (
	ShippingType_name = map[int32]string{
		0: "SHIPPING_TYPE_UNSPECIFIED",
		1: "SHIPPING_TYPE_DIGITAL",
		2: "SHIPPING_TYPE_PHYSICAL",
		3: "SHIPPING_TYPE_EXPRESS",
	}
	ShippingType_value = map[string]int32{
		"SHIPPING_TYPE_UNSPECIFIED": 0,
		"SHIPPING_TYPE_DIGITAL":     1,
		"SHIPPING_TYPE_PHYSICAL":    2,
		"SHIPPING_TYPE_EXPRESS":     3,
	}
)

func (x ShippingType) Enum() *ShippingType {
	p := new(ShippingType)
	*p = x
	return p
}

func (x ShippingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_complex_validation_proto_enumTypes[0].Descriptor()
}

func (ShippingType) Type() protoreflect.EnumType {
	return &file_proto_complex_validation_proto_enumTypes[0]
}

func (x ShippingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingType.Descriptor instead.
func (ShippingType) EnumDescriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{0}
}

// Relationship represents emergency contact relationship types
type Relationship int32

const (
	Relationship_RELATIONSHIP_UNSPECIFIED Relationship = 0
	Relationship_RELATIONSHIP_SPOUSE      Relationship = 1
	Relationship_RELATIONSHIP_PARENT      Relationship = 2
	Relationship_RELATIONSHIP_SIBLING     Relationship = 3
	Relationship_RELATIONSHIP_FRIEND      Relationship = 4
	Relationship_RELATIONSHIP_OTHER       Relationship = 5
)

// Enum value maps for Relationship.
var (
	Relationship_name = map[int32]string{
		0: "RELATIONSHIP_UNSPECIFIED",
		1: "RELATIONSHIP_SPOUSE",
		2: "RELATIONSHIP_PARENT",
		3: "RELATIONSHIP_SIBLING",
		4: "RELATIONSHIP_FRIEND",
		5: "RELATIONSHIP_OTHER",
	}
	Relationship_value = map[string]int32{
		"RELATIONSHIP_UNSPECIFIED": 0,
		"RELATIONSHIP_SPOUSE":      1,
		"RELATIONSHIP_PARENT":      2,
		"RELATIONSHIP_SIBLING":     3,
		"RELATIONSHIP_FRIEND":      4,
		"RELATIONSHIP_OTHER":       5,
	}
)

func (x Relationship) Enum() *Relationship {
	p := new(Relationship)
	*p = x
	return p
}

func (x Relationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relationship) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_complex_validation_proto_enumTypes[1].Descriptor()
}

func (Relationship) Type() protoreflect.EnumType {
	return &file_proto_complex_validation_proto_enumTypes[1]
}

func (x Relationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Relationship.Descriptor instead.
func (Relationship) EnumDescriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{1}
}

// CustomerInfo represents customer information with nested validations
type CustomerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email must be a valid email
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// phone must match phone pattern
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// address is optional but may be required by parent message
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// name is required
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	mi := &file_proto_complex_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CustomerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// OrderItem represents an item in an order with conditional validation
type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// productId is required
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// quantity must be at least 1
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// price must be positive
	Price float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	// discount is optional but required when quantity > 10
	Discount      *float64 `protobuf:"fixed64,4,opt,name=discount,proto3,oneof" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_complex_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetDiscount() float64 {
	if x != nil && x.Discount != nil {
		return *x.Discount
	}
	return 0
}

// ShippingInfo represents shipping information with conditional address requirement
type ShippingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type determines if address is required
	Type ShippingType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ShippingType" json:"type,omitempty"`
	// address is required when type is PHYSICAL or EXPRESS
	Address *string `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// trackingNumber is optional
	TrackingNumber string `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShippingInfo) Reset() {
	*x = ShippingInfo{}
	mi := &file_proto_complex_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingInfo) ProtoMessage() {}

func (x *ShippingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingInfo.ProtoReflect.Descriptor instead.
func (*ShippingInfo) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingInfo) GetType() ShippingType {
	if x != nil {
		return x.Type
	}
	return ShippingType_SHIPPING_TYPE_UNSPECIFIED
}

func (x *ShippingInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *ShippingInfo) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

// ComplexOrder demonstrates complex nested validation with CEL
type ComplexOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// customer information
	Customer *CustomerInfo `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	// order items (at least 1 required)
	Items []*OrderItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	// shipping information
	Shipping *ShippingInfo `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	// total must match sum of items
	Total         float64 `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexOrder) Reset() {
	*x = ComplexOrder{}
	mi := &file_proto_complex_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexOrder) ProtoMessage() {}

func (x *ComplexOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexOrder.ProtoReflect.Descriptor instead.
func (*ComplexOrder) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ComplexOrder) GetCustomer() *CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *ComplexOrder) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ComplexOrder) GetShipping() *ShippingInfo {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *ComplexOrder) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// PersonalInfo represents personal information with age validation
type PersonalInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// email must be valid
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// phone must match pattern
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// dateOfBirth is required
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_proto_complex_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonalInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalInfo) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

// WorkInfo represents work-related information
type WorkInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// department is required
	Department string `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	// salary must be non-negative
	Salary float64 `protobuf:"fixed64,2,opt,name=salary,proto3" json:"salary,omitempty"`
	// startDate must be after dateOfBirth (validated in parent)
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkInfo) Reset() {
	*x = WorkInfo{}
	mi := &file_proto_complex_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkInfo) ProtoMessage() {}

func (x *WorkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkInfo.ProtoReflect.Descriptor instead.
func (*WorkInfo) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{5}
}

func (x *WorkInfo) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *WorkInfo) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *WorkInfo) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

// EmergencyContact represents emergency contact information
type EmergencyContact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// relationship is required
	Relationship Relationship `protobuf:"varint,2,opt,name=relationship,proto3,enum=proto.Relationship" json:"relationship,omitempty"`
	// phone is required when relationship is SPOUSE
	Phone         string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyContact) Reset() {
	*x = EmergencyContact{}
	mi := &file_proto_complex_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyContact) ProtoMessage() {}

func (x *EmergencyContact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyContact.ProtoReflect.Descriptor instead.
func (*EmergencyContact) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{6}
}

func (x *EmergencyContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergencyContact) GetRelationship() Relationship {
	if x != nil {
		return x.Relationship
	}
	return Relationship_RELATIONSHIP_UNSPECIFIED
}

func (x *EmergencyContact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// EmployeeProfile demonstrates deep nesting with multiple CEL constraints
type EmployeeProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// personalInfo is required
	PersonalInfo *PersonalInfo `protobuf:"bytes,1,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	// workInfo is required
	WorkInfo *WorkInfo `protobuf:"bytes,2,opt,name=work_info,json=workInfo,proto3" json:"work_info,omitempty"`
	// emergencyContact is required
	EmergencyContact *EmergencyContact `protobuf:"bytes,3,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmployeeProfile) Reset() {
	*x = EmployeeProfile{}
	mi := &file_proto_complex_validation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeProfile) ProtoMessage() {}

func (x *EmployeeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeProfile.ProtoReflect.Descriptor instead.
func (*EmployeeProfile) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{7}
}

func (x *EmployeeProfile) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *EmployeeProfile) GetWorkInfo() *WorkInfo {
	if x != nil {
		return x.WorkInfo
	}
	return nil
}

func (x *EmployeeProfile) GetEmergencyContact() *EmergencyContact {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

// InventoryItem represents an inventory item with validation
type InventoryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// itemId is required
	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// name is required
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// quantity must be non-negative
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// price must be positive
	Price         float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_complex_validation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{8}
}

func (x *InventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Warehouse represents a warehouse with inventory
type Warehouse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// warehouseId is required
	WarehouseId string `protobuf:"bytes,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	// location is required
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// items is a repeated field
	Items []*InventoryItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// capacity is the maximum number of items
	Capacity      int32 `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_proto_complex_validation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_complex_validation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_proto_complex_validation_proto_rawDescGZIP(), []int{9}
}

func (x *Warehouse) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *Warehouse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Warehouse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Warehouse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_proto_complex_validation_proto protoreflect.FileDescriptor

const file_proto_complex_validation_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/complex_validation.proto\x12\x05proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\fCustomerInfo\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x122\n" +
	"\x05phone\x18\x02 \x01(\tB\x1c\xbaH\x19\xc8\x01\x01r\x142\x12^\\+?[1-9]\\d{1,14}$R\x05phone\x12$\n" +
	"\aaddress\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\n" +
	"\x18\xf4\x03R\aaddress\x12 \n" +
	"\x04name\x18\x04 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x18dR\x04name\"\xda\x02\n" +
	"\tOrderItem\x12+\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x182R\tproductId\x12)\n" +
	"\bquantity\x18\x02 \x01(\x05B\r\xbaH\n" +
	"\xc8\x01\x01\x1a\x05\x18\xe8\a(\x01R\bquantity\x12'\n" +
	"\x05price\x18\x03 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x128\n" +
	"\bdiscount\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00H\x00R\bdiscount\x88\x01\x01:\x84\x01\xbaH\x80\x01\x1a~\n" +
	"\x1adiscount_required_for_bulk\x125discount is required when quantity is greater than 10\x1a)this.quantity <= 10 || has(this.discount)B\v\n" +
	"\t_discount\"\x9e\x03\n" +
	"\fShippingInfo\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.proto.ShippingTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12)\n" +
	"\aaddress\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\n" +
	"\x18\xf4\x03H\x00R\aaddress\x88\x01\x01\x120\n" +
	"\x0ftracking_number\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18dR\x0etrackingNumber:\xee\x01\xbaH\xea\x01\x1a\xe7\x01\n" +
	"\x1daddress_required_for_physical\x12=address is required when shipping type is PHYSICAL or EXPRESS\x1a\x86\x01(this.type != proto.ShippingType.SHIPPING_TYPE_PHYSICAL && this.type != proto.ShippingType.SHIPPING_TYPE_EXPRESS) || has(this.address)B\n" +
	"\n" +
	"\b_address\"\xd8\x05\n" +
	"\fComplexOrder\x127\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.proto.CustomerInfoB\x06\xbaH\x03\xc8\x01\x01R\bcustomer\x125\n" +
	"\x05items\x18\x02 \x03(\v2\x10.proto.OrderItemB\r\xbaH\n" +
	"\xc8\x01\x01\x92\x01\x04\b\x01\x10dR\x05items\x127\n" +
	"\bshipping\x18\x03 \x01(\v2\x13.proto.ShippingInfoB\x06\xbaH\x03\xc8\x01\x01R\bshipping\x12'\n" +
	"\x05total\x18\x04 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05total:\xf5\x03\xbaH\xf1\x03\x1a\x87\x02\n" +
	"\x19customer_address_required\x12Fcustomer.address is required when shipping.type is PHYSICAL or EXPRESS\x1a\xa1\x01(this.shipping.type != proto.ShippingType.SHIPPING_TYPE_PHYSICAL && this.shipping.type != proto.ShippingType.SHIPPING_TYPE_EXPRESS) || has(this.customer.address)\x1a\xe4\x01\n" +
	"\x13total_matches_items\x12Ztotal must equal the sum of (item.price * item.quantity) minus item.discount for all items\x1aqthis.total == this.items.map(item, item.price * item.quantity - (has(item.discount) ? item.discount : 0.0)).sum()\"\xce\x01\n" +
	"\fPersonalInfo\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x18dR\x04name\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x122\n" +
	"\x05phone\x18\x03 \x01(\tB\x1c\xbaH\x19\xc8\x01\x01r\x142\x12^\\+?[1-9]\\d{1,14}$R\x05phone\x12F\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vdateOfBirth\"\xa6\x01\n" +
	"\bWorkInfo\x12,\n" +
	"\n" +
	"department\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x182R\n" +
	"department\x12)\n" +
	"\x06salary\x18\x02 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x06salary\x12A\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tstartDate\"\xcf\x02\n" +
	"\x10EmergencyContact\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x18dR\x04name\x12D\n" +
	"\frelationship\x18\x02 \x01(\x0e2\x13.proto.RelationshipB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\frelationship\x12/\n" +
	"\x05phone\x18\x03 \x01(\tB\x19\xbaH\x16r\x142\x12^\\+?[1-9]\\d{1,14}$R\x05phone:\xa1\x01\xbaH\x9d\x01\x1a\x9a\x01\n" +
	"\x19phone_required_for_spouse\x12-phone is required when relationship is SPOUSE\x1aNthis.relationship != proto.Relationship.RELATIONSHIP_SPOUSE || has(this.phone)\"\xe1\x03\n" +
	"\x0fEmployeeProfile\x12@\n" +
	"\rpersonal_info\x18\x01 \x01(\v2\x13.proto.PersonalInfoB\x06\xbaH\x03\xc8\x01\x01R\fpersonalInfo\x124\n" +
	"\twork_info\x18\x02 \x01(\v2\x0f.proto.WorkInfoB\x06\xbaH\x03\xc8\x01\x01R\bworkInfo\x12L\n" +
	"\x11emergency_contact\x18\x03 \x01(\v2\x17.proto.EmergencyContactB\x06\xbaH\x03\xc8\x01\x01R\x10emergencyContact:\x87\x02\xbaH\x83\x02\x1au\n" +
	"\x0eminimum_age_18\x12&employee must be at least 18 years old\x1a;now() - this.personal_info.date_of_birth >= duration('18y')\x1a\x89\x01\n" +
	"\x16start_date_after_birth\x121work startDate must be after personal dateOfBirth\x1a<this.work_info.start_date > this.personal_info.date_of_birth\"\xb8\x01\n" +
	"\rInventoryItem\x123\n" +
	"\aitem_id\x18\x01 \x01(\tB\x1a\xbaH\x17\xc8\x01\x01r\x12\x10\x03\x18\x142\f^[A-Z0-9-]+$R\x06itemId\x12!\n" +
	"\x04name\x18\x02 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\xc8\x01R\x04name\x12&\n" +
	"\bquantity\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\xc8\x01\x01\x1a\x02(\x00R\bquantity\x12'\n" +
	"\x05price\x18\x04 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\"\xed\x02\n" +
	"\tWarehouse\x12?\n" +
	"\fwarehouse_id\x18\x01 \x01(\tB\x1c\xbaH\x19\xc8\x01\x01r\x14\x10\x04\x18\x142\x0e^WH-[A-Z0-9]+$R\vwarehouseId\x12(\n" +
	"\blocation\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18dR\blocation\x127\n" +
	"\x05items\x18\x03 \x03(\v2\x14.proto.InventoryItemB\v\xbaH\b\x92\x01\x05\b\x00\x10\x90NR\x05items\x12&\n" +
	"\bcapacity\x18\x04 \x01(\x05B\n" +
	"\xbaH\a\xc8\x01\x01\x1a\x02 \x00R\bcapacity:\x93\x01\xbaH\x8f\x01\x1a\x8c\x01\n" +
	"\x0ecapacity_check\x12>total quantity of all items must not exceed warehouse capacity\x1a:this.items.map(item, item.quantity).sum() <= this.capacity*\x7f\n" +
	"\fShippingType\x12\x1d\n" +
	"\x19SHIPPING_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SHIPPING_TYPE_DIGITAL\x10\x01\x12\x1a\n" +
	"\x16SHIPPING_TYPE_PHYSICAL\x10\x02\x12\x19\n" +
	"\x15SHIPPING_TYPE_EXPRESS\x10\x03*\xa9\x01\n" +
	"\fRelationship\x12\x1c\n" +
	"\x18RELATIONSHIP_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RELATIONSHIP_SPOUSE\x10\x01\x12\x17\n" +
	"\x13RELATIONSHIP_PARENT\x10\x02\x12\x18\n" +
	"\x14RELATIONSHIP_SIBLING\x10\x03\x12\x17\n" +
	"\x13RELATIONSHIP_FRIEND\x10\x04\x12\x16\n" +
	"\x12RELATIONSHIP_OTHER\x10\x05B\"Z validation-service/backend/protob\x06proto3"

var (
	file_proto_complex_validation_proto_rawDescOnce sync.Once
	file_proto_complex_validation_proto_rawDescData []byte
)

func file_proto_complex_validation_proto_rawDescGZIP() []byte {
	file_proto_complex_validation_proto_rawDescOnce.Do(func() {
		file_proto_complex_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_complex_validation_proto_rawDesc), len(file_proto_complex_validation_proto_rawDesc)))
	})
	return file_proto_complex_validation_proto_rawDescData
}

var file_proto_complex_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_complex_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_complex_validation_proto_goTypes = []any{
	(ShippingType)(0),             // 0: proto.ShippingType
	(Relationship)(0),             // 1: proto.Relationship
	(*CustomerInfo)(nil),          // 2: proto.CustomerInfo
	(*OrderItem)(nil),             // 3: proto.OrderItem
	(*ShippingInfo)(nil),          // 4: proto.ShippingInfo
	(*ComplexOrder)(nil),          // 5: proto.ComplexOrder
	(*PersonalInfo)(nil),          // 6: proto.PersonalInfo
	(*WorkInfo)(nil),              // 7: proto.WorkInfo
	(*EmergencyContact)(nil),      // 8: proto.EmergencyContact
	(*EmployeeProfile)(nil),       // 9: proto.EmployeeProfile
	(*InventoryItem)(nil),         // 10: proto.InventoryItem
	(*Warehouse)(nil),             // 11: proto.Warehouse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_complex_validation_proto_depIdxs = []int32{
	0,  // 0: proto.ShippingInfo.type:type_name -> proto.ShippingType
	2,  // 1: proto.ComplexOrder.customer:type_name -> proto.CustomerInfo
	3,  // 2: proto.ComplexOrder.items:type_name -> proto.OrderItem
	4,  // 3: proto.ComplexOrder.shipping:type_name -> proto.ShippingInfo
	12, // 4: proto.PersonalInfo.date_of_birth:type_name -> google.protobuf.Timestamp
	12, // 5: proto.WorkInfo.start_date:type_name -> google.protobuf.Timestamp
	1,  // 6: proto.EmergencyContact.relationship:type_name -> proto.Relationship
	6,  // 7: proto.EmployeeProfile.personal_info:type_name -> proto.PersonalInfo
	7,  // 8: proto.EmployeeProfile.work_info:type_name -> proto.WorkInfo
	8,  // 9: proto.EmployeeProfile.emergency_contact:type_name -> proto.EmergencyContact
	10, // 10: proto.Warehouse.items:type_name -> proto.InventoryItem
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_complex_validation_proto_init() }
func file_proto_complex_validation_proto_init() {
	if File_proto_complex_validation_proto != nil {
		return
	}
	file_proto_complex_validation_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_complex_validation_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_complex_validation_proto_rawDesc), len(file_proto_complex_validation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_complex_validation_proto_goTypes,
		DependencyIndexes: file_proto_complex_validation_proto_depIdxs,
		EnumInfos:         file_proto_complex_validation_proto_enumTypes,
		MessageInfos:      file_proto_complex_validation_proto_msgTypes,
	}.Build()
	File_proto_complex_validation_proto = out.File
	file_proto_complex_validation_proto_goTypes = nil
	file_proto_complex_validation_proto_depIdxs = nil
}
