// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/delete_task.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeleteTask represents a request to delete a task with an optional comment
type DeleteTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the unique identifier of the task to delete (required, min 1 character)
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// comment is an optional reason or note for deleting the task (max 1000 characters)
	Comment       string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTask) Reset() {
	*x = DeleteTask{}
	mi := &file_proto_delete_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTask) ProtoMessage() {}

func (x *DeleteTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delete_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTask.ProtoReflect.Descriptor instead.
func (*DeleteTask) Descriptor() ([]byte, []int) {
	return file_proto_delete_task_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeleteTask) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_proto_delete_task_proto protoreflect.FileDescriptor

const file_proto_delete_task_proto_rawDesc = "" +
	"\n" +
	"\x17proto/delete_task.proto\x12\x05proto\x1a\x1bbuf/validate/validate.proto\"W\n" +
	"\n" +
	"DeleteTask\x12%\n" +
	"\atask_id\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\x06taskId\x12\"\n" +
	"\acomment\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\acommentB\"Z validation-service/backend/protob\x06proto3"

var (
	file_proto_delete_task_proto_rawDescOnce sync.Once
	file_proto_delete_task_proto_rawDescData []byte
)

func file_proto_delete_task_proto_rawDescGZIP() []byte {
	file_proto_delete_task_proto_rawDescOnce.Do(func() {
		file_proto_delete_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_delete_task_proto_rawDesc), len(file_proto_delete_task_proto_rawDesc)))
	})
	return file_proto_delete_task_proto_rawDescData
}

var file_proto_delete_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_delete_task_proto_goTypes = []any{
	(*DeleteTask)(nil), // 0: proto.DeleteTask
}
var file_proto_delete_task_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_delete_task_proto_init() }
func file_proto_delete_task_proto_init() {
	if File_proto_delete_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_delete_task_proto_rawDesc), len(file_proto_delete_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_delete_task_proto_goTypes,
		DependencyIndexes: file_proto_delete_task_proto_depIdxs,
		MessageInfos:      file_proto_delete_task_proto_msgTypes,
	}.Build()
	File_proto_delete_task_proto = out.File
	file_proto_delete_task_proto_goTypes = nil
	file_proto_delete_task_proto_depIdxs = nil
}
