// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/simple_validation.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents different status types
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_PENDING     Status = 3
	Status_STATUS_SUSPENDED   Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_PENDING",
		4: "STATUS_SUSPENDED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_PENDING":     3,
		"STATUS_SUSPENDED":   4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_simple_validation_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_simple_validation_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{0}
}

// SimpleUser represents a user with basic string, email, and numeric validations
type SimpleUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name must be between 3 and 50 characters
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// email must be a valid email format
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// age must be between 18 and 120
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// contactInfo is an optional nested message
	ContactInfo   *ContactInfo `protobuf:"bytes,4,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleUser) Reset() {
	*x = SimpleUser{}
	mi := &file_proto_simple_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUser) ProtoMessage() {}

func (x *SimpleUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUser.ProtoReflect.Descriptor instead.
func (*SimpleUser) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SimpleUser) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SimpleUser) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

// ContactInfo represents contact information with phone and address
type ContactInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// phone must match phone number pattern (optional)
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	// address must be at most 500 characters
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// country code must be exactly 2 uppercase letters
	CountryCode   string `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_proto_simple_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContactInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

// Product represents a product with name, price, and quantity
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is required, 1-100 characters
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// price must be positive (minimum 0.01)
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// quantity must be at least 1
	Quantity      int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_simple_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ProductList contains a list of products
type ProductList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// products is a repeated field with at least 1 item
	Products      []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_proto_simple_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// StatusMessage demonstrates enum validation
type StatusMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status must be a defined enum value (not UNSPECIFIED)
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	// message is required when status is SUSPENDED
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_proto_simple_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{4}
}

func (x *StatusMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *StatusMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NumericTypes demonstrates various numeric validations
type NumericTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int32_value must be between -1000 and 1000
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// int64_value must be positive
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// float_value must be between 0.0 and 1.0
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value must be between -100.0 and 100.0
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// uint32_value must be at most 10000
	Uint32Value uint32 `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	// uint64_value must be at least 1
	Uint64Value   uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericTypes) Reset() {
	*x = NumericTypes{}
	mi := &file_proto_simple_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericTypes) ProtoMessage() {}

func (x *NumericTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericTypes.ProtoReflect.Descriptor instead.
func (*NumericTypes) Descriptor() ([]byte, []int) {
	return file_proto_simple_validation_proto_rawDescGZIP(), []int{5}
}

func (x *NumericTypes) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *NumericTypes) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *NumericTypes) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *NumericTypes) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *NumericTypes) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *NumericTypes) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

var File_proto_simple_validation_proto protoreflect.FileDescriptor

const file_proto_simple_validation_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/simple_validation.proto\x12\x05proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x01\n" +
	"\n" +
	"SimpleUser\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xbaH\x17\xc8\x01\x01r\x12\x10\x03\x1822\f^[a-zA-Z ]+$R\x04name\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12\x1e\n" +
	"\x03age\x18\x03 \x01(\x05B\f\xbaH\t\xc8\x01\x01\x1a\x04\x18x(\x12R\x03age\x125\n" +
	"\fcontact_info\x18\x04 \x01(\v2\x12.proto.ContactInfoR\vcontactInfo\"\x9b\x01\n" +
	"\vContactInfo\x12/\n" +
	"\x05phone\x18\x01 \x01(\tB\x19\xbaH\x16r\x142\x12^\\+?[1-9]\\d{1,14}$R\x05phone\x12\"\n" +
	"\aaddress\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\aaddress\x127\n" +
	"\fcountry_code\x18\x03 \x01(\tB\x14\xbaH\x11r\x0f2\n" +
	"^[A-Z]{2}$\x98\x01\x02R\vcountryCode\"|\n" +
	"\aProduct\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\x04name\x12'\n" +
	"\x05price\x18\x02 \x01(\x01B\x11\xbaH\x0e\xc8\x01\x01\x12\t){\x14\xaeG\xe1z\x84?R\x05price\x12&\n" +
	"\bquantity\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\xc8\x01\x01\x1a\x02(\x01R\bquantity\"E\n" +
	"\vProductList\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x0e.proto.ProductB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10dR\bproducts\"i\n" +
	"\rStatusMessage\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.proto.StatusB\r\xbaH\n" +
	"\xc8\x01\x01\x82\x01\x04\x10\x01 \x00R\x06status\x12\"\n" +
	"\amessage\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\amessage\"\xb5\x02\n" +
	"\fNumericTypes\x124\n" +
	"\vint32_value\x18\x01 \x01(\x05B\x13\xbaH\x10\x1a\x0e\x18\xe8\a(\x98\xf8\xff\xff\xff\xff\xff\xff\xff\x01R\n" +
	"int32Value\x12(\n" +
	"\vint64_value\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\n" +
	"int64Value\x120\n" +
	"\vfloat_value\x18\x03 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\n" +
	"floatValue\x12:\n" +
	"\fdouble_value\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00Y\xc0R\vdoubleValue\x12+\n" +
	"\fuint32_value\x18\x05 \x01(\rB\b\xbaH\x05*\x03\x18\x90NR\vuint32Value\x12*\n" +
	"\fuint64_value\x18\x06 \x01(\x04B\a\xbaH\x042\x02(\x01R\vuint64Value*r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04B\"Z validation-service/backend/protob\x06proto3"

var (
	file_proto_simple_validation_proto_rawDescOnce sync.Once
	file_proto_simple_validation_proto_rawDescData []byte
)

func file_proto_simple_validation_proto_rawDescGZIP() []byte {
	file_proto_simple_validation_proto_rawDescOnce.Do(func() {
		file_proto_simple_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_validation_proto_rawDesc), len(file_proto_simple_validation_proto_rawDesc)))
	})
	return file_proto_simple_validation_proto_rawDescData
}

var file_proto_simple_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_simple_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_simple_validation_proto_goTypes = []any{
	(Status)(0),           // 0: proto.Status
	(*SimpleUser)(nil),    // 1: proto.SimpleUser
	(*ContactInfo)(nil),   // 2: proto.ContactInfo
	(*Product)(nil),       // 3: proto.Product
	(*ProductList)(nil),   // 4: proto.ProductList
	(*StatusMessage)(nil), // 5: proto.StatusMessage
	(*NumericTypes)(nil),  // 6: proto.NumericTypes
}
var file_proto_simple_validation_proto_depIdxs = []int32{
	2, // 0: proto.SimpleUser.contact_info:type_name -> proto.ContactInfo
	3, // 1: proto.ProductList.products:type_name -> proto.Product
	0, // 2: proto.StatusMessage.status:type_name -> proto.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_simple_validation_proto_init() }
func file_proto_simple_validation_proto_init() {
	if File_proto_simple_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_validation_proto_rawDesc), len(file_proto_simple_validation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_validation_proto_goTypes,
		DependencyIndexes: file_proto_simple_validation_proto_depIdxs,
		EnumInfos:         file_proto_simple_validation_proto_enumTypes,
		MessageInfos:      file_proto_simple_validation_proto_msgTypes,
	}.Build()
	File_proto_simple_validation_proto = out.File
	file_proto_simple_validation_proto_goTypes = nil
	file_proto_simple_validation_proto_depIdxs = nil
}
